### ISSUE TITLE
Clean returning wrong size in lfs-pointer

### ISSUE THREAD

**Issue by rem0te** [zezba9000/Git-Game-GUI#1]
I used your code as reference for my own project, and I spent a lot of time trying to figure out why clean was not working correctly.  Turns out you have to provide path to clean otherwise it just read the first 1024 byte and think this is the correct size.

**Comment by zezba9000** [comment]
Are you saying there is a bug in this project or just letting me know you're referencing code from this project to fix your own?

Reference any code you want, keep in mind this prototype version is being replaced with: https://github.com/reignstudios/Git-It-GUI

If you find a bug with how I was doing the clean filter I would like to know what the fix is.

**Comment by rem0te** [comment]
Its a bug, and its valid for Git-It-GUI as well (sorry, I should have flagged it there instead)

your process argument doesnt contain path to file.  While its optional for smudge, it is crucial to clean otherwise it cannot determine file size.

You'll want to do something like this:

`process.StartInfo.Arguments = string.Format("{0} {1}", mode == FilterMode.Clean ? "clean" : "smudge", path);`

**Comment by zezba9000** [comment]
Ok tnx for the info. I'll take a look.

**Comment by zezba9000** [comment]
Have pushed a fix for this. Thanks again for pointing this out!
